// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// neogro
DataFrame neogro(int NK, int MAXIT, double TOL, double TOL1, double NEG, double ZETA, double beta, double sigma, double alpha, double delta, bool verbose);
RcppExport SEXP _neogro_neogro(SEXP NKSEXP, SEXP MAXITSEXP, SEXP TOLSEXP, SEXP TOL1SEXP, SEXP NEGSEXP, SEXP ZETASEXP, SEXP betaSEXP, SEXP sigmaSEXP, SEXP alphaSEXP, SEXP deltaSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type NK(NKSEXP);
    Rcpp::traits::input_parameter< int >::type MAXIT(MAXITSEXP);
    Rcpp::traits::input_parameter< double >::type TOL(TOLSEXP);
    Rcpp::traits::input_parameter< double >::type TOL1(TOL1SEXP);
    Rcpp::traits::input_parameter< double >::type NEG(NEGSEXP);
    Rcpp::traits::input_parameter< double >::type ZETA(ZETASEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(neogro(NK, MAXIT, TOL, TOL1, NEG, ZETA, beta, sigma, alpha, delta, verbose));
    return rcpp_result_gen;
END_RCPP
}
// k_steady_state
double k_steady_state(double alpha, double beta, double delta);
RcppExport SEXP _neogro_k_steady_state(SEXP alphaSEXP, SEXP betaSEXP, SEXP deltaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    rcpp_result_gen = Rcpp::wrap(k_steady_state(alpha, beta, delta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_neogro_neogro", (DL_FUNC) &_neogro_neogro, 11},
    {"_neogro_k_steady_state", (DL_FUNC) &_neogro_k_steady_state, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_neogro(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
