# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test Golden Section Maximization
#'
#' @param ax,bx,cx interval and starting value for golden section
#'     search
#' @param tol tolerance for stopping criterion
#'
#' @return A `Numeric`
#'
#' @name test-golden
#'
#' @examples
#' test_golden()
NULL

#' @rdname test-golden
#' @export
test_golden <- function(ax = -2.2, bx = 0.0, cx = 10.0, tol = .001) {
    .Call(`_neogro_test_golden`, ax, bx, cx, tol)
}

#' @rdname test-golden
#' @export
test_golden2 <- function(ax = -2.2, bx = 0.0, cx = 10.0, tol = .001) {
    .Call(`_neogro_test_golden2`, ax, bx, cx, tol)
}

#' Solve the Neoclassical Growth Model
#'
#' This function solves a standard deterministic neoclassical growth model
#' using value function iteration. The solution returns the optimal
#' policy functions and the value function over a discretized grid of capital.
#'
#' The model assumes a Cobb-Douglas production function
#' \eqn{f(k) = k^{\alpha}}, and solves for the household's
#' optimal savings policy under given parameters. Convergence is controlled
#' by the tolerances \code{TOL} and \code{TOL1}.
#'
#' @param NK Integer. Number of grid points for capital (default = 200).
#' @param MAXIT Integer. Maximum number of value function iterations (default = 500).
#' @param TOL Numeric. Convergence tolerance for value function (default = 1e-5).
#' @param TOL1 Numeric. Convergence tolerance for golden section search (default = 1e-7).
#' @param NEG Numeric. Large negative number used as a placeholder for infeasible utility (default = -1e10).
#' @param ZETA Numeric. Relaxation parameter for value function updates (default = 0.05).
#' @param beta Numeric. Discount factor \eqn{\beta} (default = 0.994).
#' @param sigma Numeric. Relative risk aversion (CRRA) parameter \eqn{\sigma} (default = 2.0).
#' @param alpha Numeric. Capital share \eqn{\alpha} in production (default = 0.28).
#' @param delta Numeric. Depreciation rate of capital \eqn{\delta} (default = 0.0).
#' @param verbose Boolean. If `true` prints the error at each iteration (default = false).
#'
#' @return A `DataFrame` with the following components:
#' \itemize{
#'   \item `k` – Capital stock.
#'   \item `v` – Value function.
#'   \item `kopt` – Optimal capital choice.
#'   \item `copt` – Optimal consumption choice.
#'   \item `iopt` – Optimal investment choice.
#'   \item `y` – output.
#'   \item `ropt` – residuals of first-order condition of optimal savings
#'       decision problem..
#' }
#'
#' @examples
#' # Solve the neoclassical growth model with default parameters
#' result <- neogro()
#' head(result)
#'
#' # Solve with custom parameters
#' result <- neogro(NK = 300, beta = 0.96, alpha = 0.33, delta = 0.05)
#' plot(result$k, result$kopt, type = "l", main = "Policy Function")
#'
#' @export
neogro <- function(NK = 200L, MAXIT = 500L, TOL = 1e-5, TOL1 = 1e-7, NEG = -1e10, ZETA = 0.05, beta = 0.994, sigma = 2.0, alpha = 0.28, delta = 0.0, verbose = FALSE) {
    .Call(`_neogro_neogro`, NK, MAXIT, TOL, TOL1, NEG, ZETA, beta, sigma, alpha, delta, verbose)
}

#' Steady State Capital Stock
#'
#' This function computes the steady state capital stock of the standard
#' deterministic neoclassical growth model
#'
#' @param beta Numeric. Discount factor \eqn{\beta}.
#' @param alpha Numeric. Capital share \eqn{\alpha} in production.
#' @param delta Numeric. Depreciation rate of capital \eqn{\delta}.
#'
#' @return A `Numeric` with the following components:
#'
#' @examples
#' k_steady_state(alpha = 0.33, beta = 0.96, delta = 0.05)
#'
#' @export
k_steady_state <- function(alpha, beta, delta) {
    .Call(`_neogro_k_steady_state`, alpha, beta, delta)
}

